{
 "title": "Air Quality TIMC",
 "time": { "from": "2023-05-22T12:04:51.197Z", "to": "2023-05-22T13:26:30.033Z" },
 "templating": {
  "list": [
   {
    "name": "deviceName",
    "query": "SHOW TAG VALUES WITH KEY = \"deviceName\""
   }
  ]
 },
 "panels": [
  { "title": "$deviceName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "deviceName" },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "temperature",
     "measurement": "data",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "alias": "humidity",
     "measurement": "data",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "PM 10",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "motion",
     "measurement": "data",
     "select": [
      [
       { "params": [ "pm10Atmospheric" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "PM 2.5",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Digital",
     "measurement": "data",
     "select": [
      [
       { "params": [ "pm2_5Atmospheric" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "PM 1",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Digital",
     "measurement": "data",
     "select": [
      [
       { "params": [ "pm1_0Atmospheric" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "temperature",
     "measurement": "data",
     "query": "SELECT mean(\"temperature\") FROM \"data\" WHERE (\"applicationName\" = 'SICONIA' AND \"devEUI\" = '4883c7df30051c1b') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    },
    {
     "alias": "dew point",
     "measurement": "data",
     "select": [
      [
       { "params": [ "dewpoint" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "alias": "humidity",
     "measurement": "data",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "alias": "pressure",
     "measurement": "data",
     "select": [
      [
       { "params": [ "pressure" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "SNR",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 11 },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "lsnr" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "fCnt",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "fCnt" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "status",
     "select": [
      [
       { "params": [ "battery" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "DataRate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "dr" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Redundancy",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "redundancy" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Redundancy",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "redundancy",
     "measurement": "data",
     "select": [
      [
       { "params": [ "redundancy" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  { "title": "$deviceName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "targets": [
    {
     "alias": "temperature",
     "measurement": "data",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 17 },
   "targets": [
    {
     "alias": "humidity",
     "measurement": "data",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "PM 10",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "motion",
     "measurement": "data",
     "select": [
      [
       { "params": [ "particuleGT10" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "PM 2.5",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Digital",
     "measurement": "data",
     "select": [
      [
       { "params": [ "particuleGT1_0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "PM 1",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Digital",
     "measurement": "data",
     "select": [
      [
       { "params": [ "particuleGT1_0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "temperature",
     "measurement": "data",
     "query": "SELECT mean(\"temperature\") FROM \"data\" WHERE (\"applicationName\" = 'SICONIA' AND \"devEUI\" = '4883c7df30051c1b') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    },
    {
     "alias": "dew point",
     "measurement": "data",
     "select": [
      [
       { "params": [ "dewpoint" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "alias": "humidity",
     "measurement": "data",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Redundancy",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "redundancy",
     "measurement": "data",
     "select": [
      [
       { "params": [ "redundancy" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 27 },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "SNR",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 27 },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "lsnr" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "fCnt",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "fCnt" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 27 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "status",
     "select": [
      [
       { "params": [ "battery" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "DataRate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "dr" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Redundancy",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "redundancy" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  }
 ]
}